/*---------------------------------------------------------------------------------------------
 *  Copyright (c) 2026 Hannah Potter. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import React, { useCallback, useMemo, useState } from 'react';
import { editContentFingerprint } from './viewerModel';
import { type HunkReference, isGlob, matchesGlob } from '../../src/github/codeTourMarkdown';
import { ChangedFileInfo } from '../../src/github/views';
import { DiffTable } from '../common/DiffTable';
import { ParsedDiffLine, parsePatch } from '../common/diffUtils';
import { OverflowMenu, type OverflowMenuItem } from '../common/OverflowMenu';
import { Tooltip } from '../common/tooltip';
import { addIcon, chevronDownIcon, eyeClosedIcon, listTree } from '../components/icon';

interface ChangedFilesOverviewProps {
	title: string;
	number: number;
	owner: string;
	repo: string;
	/** PR base commit SHA at the moment the changes view was opened. Stamped onto hunk drag payloads so dropped hunks seed the tour document's `baseSha`. */
	baseSha?: string;
	/** PR head commit SHA at the moment the changes view was opened. Same propagation as `baseSha`, plus the future outdated-detection feature's primary tour-level anchor. */
	headSha?: string;
	files: ChangedFileInfo[];
	/**
	 * Author-marked exclusion markers from the parsed tour. PR hunks that
	 * match any marker (exact-range, whole-file, or glob) are treated as
	 * "covered" for the coverage progress bar / per-file styling, so adding
	 * an exclusion immediately clears its hunk from the missing list.
	 */
	exclusions?: ReadonlyArray<{ file: string; startLine?: number; endLine?: number }>;
	onHunkAdd: (hunks: HunkReference[], mode: 'active' | 'quickpick') => void;
	/**
	 * Excludes the hunk identified by `(file, startLine, endLine)` from the
	 * tour's drift / coverage report. Provider prompts for an optional reason
	 * and appends a `<!-- changetour:exclude … -->` marker to the tour file.
	 */
	onHunkExclude?: (file: string, startLine: number, endLine: number, fp: string | undefined) => void;
	/**
	 * Excludes every PR hunk in the given file from the tour's drift /
	 * coverage report. Provider prompts for an optional reason and appends a
	 * whole-file `<!-- changetour:exclude file="..." -->` marker (no `lines=`).
	 * Use this for autogenerated files / directories of mechanical output
	 * whose hunk ranges shift on every regen.
	 */
	onFileExclude?: (file: string) => void;
	activeNodeContext?: string;
	codeTourHunks?: HunkReference[];
	onAddAllMissing?: (hunks: HunkReference[]) => void;
	/** Inline vs. side-by-side rendering for the per-file diff tables. Comes from the same `diffLayout` state as the rest of the editor so the layout toggle covers the hunk selector too. */
	diffLayout?: 'inline' | 'sideBySide';
}

function statusLabel(status: string): { text: string; className: string } {
	switch (status) {
		case 'added': return { text: 'A', className: 'added' };
		case 'removed': return { text: 'D', className: 'removed' };
		case 'modified': return { text: 'M', className: 'modified' };
		case 'renamed': return { text: 'R', className: 'renamed' };
		case 'copied': return { text: 'C', className: 'modified' };
		default: return { text: 'M', className: 'modified' };
	}
}

function splitPath(fileName: string): { dir: string; base: string } {
	const lastSlash = fileName.lastIndexOf('/');
	if (lastSlash === -1) {
		return { dir: '', base: fileName };
	}
	return {
		dir: fileName.substring(0, lastSlash + 1),
		base: fileName.substring(lastSlash + 1),
	};
}

function normalizeSearchText(value: string | undefined): string {
	return (value ?? '').toLowerCase();
}

function buildFileSearchText(file: ChangedFileInfo): string {
	return normalizeSearchText([
		file.fileName,
		file.previousFileName,
		file.status,
		file.patch,
	].filter((part): part is string => !!part).join('\n'));
}

function matchesFileSearch(file: ChangedFileInfo, query: string): boolean {
	if (!query) {
		return true;
	}
	return buildFileSearchText(file).includes(query);
}

/**
 * Compute the new-side line range covered by each hunk section so we can
 * attach drag data to hunk-header rows AND match against the keys produced
 * by the in-extension hunk tools (which also use new-side ranges). Using
 * the new side keeps the coverage logic consistent with how
 * `resolveHunkInActivePR` matches PR hunks (h.newLineNumber).
 */
function computeHunkRanges(lines: ParsedDiffLine[]): Map<number, { startLine: number; endLine: number }> {
	const ranges = new Map<number, { startLine: number; endLine: number }>();
	let currentHeaderIdx = -1;
	let startLine = 0;
	let endLine = 0;

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (line.type === 'hunk-header') {
			// Close previous hunk
			if (currentHeaderIdx >= 0) {
				ranges.set(currentHeaderIdx, { startLine, endLine });
			}
			currentHeaderIdx = i;
			const match = /^@@\s+-\d+(?:,\d+)?\s+\+(?<start>\d+)/.exec(line.content);
			startLine = match ? parseInt(match.groups!.start, 10) : 0;
			// A pure-deletion hunk has zero new-side lines; report an empty range.
			endLine = startLine - 1;
		} else {
			// Skip deletion lines - they have no new-side line number, so they
			// must not extend this hunk's new-side range.
			if (line.newLine !== undefined && line.newLine > endLine) {
				endLine = line.newLine;
			}
		}
	}
	if (currentHeaderIdx >= 0) {
		ranges.set(currentHeaderIdx, { startLine, endLine });
	}
	return ranges;
}

function DiffView({ patch, fileName, previousFile, blobSha, prNumber, prOwner, prRepo, baseSha, headSha, onHunkAdd, onHunkExclude, activeNodeContext, coveredHunksSet, selectedHunksSet, onHunkSelect, onClearHunksSelection, searchQuery, searchActive, hideCovered, diffLayout }: { patch: string; fileName: string; previousFile?: string; blobSha?: string; prNumber: number; prOwner: string; prRepo: string; baseSha?: string; headSha?: string; onHunkAdd: (hunks: HunkReference[], mode: 'active' | 'quickpick') => void, onHunkExclude?: (file: string, startLine: number, endLine: number, fp: string | undefined) => void, activeNodeContext?: string, coveredHunksSet?: Set<string>, selectedHunksSet: Set<string>, onHunkSelect: (k: string, s: boolean) => void, onClearHunksSelection: () => void, searchQuery: string, searchActive: boolean, hideCovered: boolean, diffLayout?: 'inline' | 'sideBySide' }) {
	const lines = parsePatch(patch);
	const rawLines = patch.split('\n');
	const hunkRanges = computeHunkRanges(lines);
	const normalizedSearchQuery = searchQuery.trim().toLowerCase();

	const searchMatchInfo = useMemo(() => {
		const matchedHeaderIndices = new Set<number>();
		const matchedLineIndices = new Set<number>();

		if (!searchActive || !normalizedSearchQuery) {
			return { matchedHeaderIndices, matchedLineIndices };
		}

		let currentHeaderIdx = -1;
		for (let i = 0; i < lines.length; i++) {
			const line = lines[i];
			const isMatch = line.content.toLowerCase().includes(normalizedSearchQuery);
			if (line.type === 'hunk-header') {
				currentHeaderIdx = i;
				if (isMatch) {
					matchedHeaderIndices.add(i);
				}
				continue;
			}

			if (isMatch) {
				matchedLineIndices.add(i);
				if (currentHeaderIdx >= 0) {
					matchedHeaderIndices.add(currentHeaderIdx);
				}
			}
		}

		return { matchedHeaderIndices, matchedLineIndices };
	}, [lines, normalizedSearchQuery, searchActive]);

	// Find the raw patch indices for each hunk header so we can extract hunk content
	const hunkRawIndices: number[] = [];
	for (let i = 0; i < rawLines.length; i++) {
		if (rawLines[i].startsWith('@@')) {
			hunkRawIndices.push(i);
		}
	}

	const handleHunkDragStart = useCallback((e: React.DragEvent, headerIdx: number) => {
		const range = hunkRanges.get(headerIdx);
		if (!range) {
			return;
		}

		// Extract the raw patch content for just this hunk
		const parsedHunkIdx = lines.slice(0, headerIdx + 1).filter(l => l.type === 'hunk-header').length - 1;
		const rawStart = hunkRawIndices[parsedHunkIdx];
		const rawEnd = parsedHunkIdx + 1 < hunkRawIndices.length
			? hunkRawIndices[parsedHunkIdx + 1]
			: rawLines.length;
		const hunkPatch = rawLines.slice(rawStart, rawEnd).join('\n');

		const payload = JSON.stringify({
			file: fileName,
			startLine: range.startLine,
			endLine: range.endLine,
			patch: hunkPatch,
			previousFile,
			baseBlob: blobSha,
			baseSha,
			headSha,
			prNumber,
			prOwner,
			prRepo
		});
		e.dataTransfer.setData('application/vnd.codetour.hunk+json', payload);
		e.dataTransfer.effectAllowed = 'copy';
	}, [hunkRanges, fileName, lines, rawLines, hunkRawIndices, previousFile, blobSha, baseSha, headSha, prNumber, prOwner, prRepo]);

	// Figure out which lines belong to covered & selected hunks so we can style/manage them
	const coveredHeaderIndices = new Set<number>();
	const selectedHeaderIndices = new Set<number>();
	hunkRanges.forEach((range, headerIdx) => {
		const key = `${fileName}:${range.startLine}:${range.endLine}`;
		if (coveredHunksSet?.has(key)) {
			coveredHeaderIndices.add(headerIdx);
		}
		if (selectedHunksSet.has(key)) {
			selectedHeaderIndices.add(headerIdx);
		}
	});

	const addHunkToEditor = useCallback((headerIdx: number, mode: 'active' | 'quickpick') => {
		const range = hunkRanges.get(headerIdx);
		if (!range) return;

		if (selectedHeaderIndices.has(headerIdx)) {
			const payloads: any[] = [];
			hunkRanges.forEach((r, idx) => {
				if (selectedHeaderIndices.has(idx)) {
					const parsedHunkIdx = lines.slice(0, idx + 1).filter(l => l.type === 'hunk-header').length - 1;
					const rawStart = hunkRawIndices[parsedHunkIdx];
					const rawEnd = parsedHunkIdx + 1 < hunkRawIndices.length
						? hunkRawIndices[parsedHunkIdx + 1]
						: rawLines.length;
					const hunkPatch = rawLines.slice(rawStart, rawEnd).join('\n');

					payloads.push({
						file: fileName,
						startLine: r.startLine,
						endLine: r.endLine,
									patch: hunkPatch,
						previousFile,
						baseBlob: blobSha,
						baseSha,
						headSha,
						prNumber,
						prOwner,
						prRepo
					});
				}
			});
			onHunkAdd(payloads, mode);
			onClearHunksSelection();
		} else {
			const parsedHunkIdx = lines.slice(0, headerIdx + 1).filter(l => l.type === 'hunk-header').length - 1;
			const rawStart = hunkRawIndices[parsedHunkIdx];
			const rawEnd = parsedHunkIdx + 1 < hunkRawIndices.length
				? hunkRawIndices[parsedHunkIdx + 1]
				: rawLines.length;
			const hunkPatch = rawLines.slice(rawStart, rawEnd).join('\n');

			const payload = {
				file: fileName,
				startLine: range.startLine,
				endLine: range.endLine,
					patch: hunkPatch,
				previousFile,
				baseBlob: blobSha,
				baseSha,
				headSha,
				prNumber,
				prOwner,
				prRepo
			};

			onHunkAdd([payload], mode);
		}
	}, [hunkRanges, fileName, lines, rawLines, hunkRawIndices, previousFile, blobSha, baseSha, headSha, prNumber, prOwner, prRepo, onHunkAdd, selectedHeaderIndices, onClearHunksSelection]);

	const handleHunkSelectToggle = useCallback((headerIdx: number, selected: boolean) => {
		const range = hunkRanges.get(headerIdx);
		if (range) {
			onHunkSelect(`${fileName}:${range.startLine}:${range.endLine}`, selected);
		}
	}, [hunkRanges, fileName, onHunkSelect]);

	const handleHunkExclude = useCallback((headerIdx: number) => {
		const range = hunkRanges.get(headerIdx);
		if (range && onHunkExclude) {
			const parsedHunkIdx = lines.slice(0, headerIdx + 1).filter(l => l.type === 'hunk-header').length - 1;
			const rawStart = hunkRawIndices[parsedHunkIdx];
			const rawEnd = parsedHunkIdx + 1 < hunkRawIndices.length
				? hunkRawIndices[parsedHunkIdx + 1]
				: rawLines.length;
			const fp = editContentFingerprint(rawLines.slice(rawStart, rawEnd).join('\n'));
			onHunkExclude(fileName, range.startLine, range.endLine, fp);
		}
	}, [hunkRanges, fileName, lines, rawLines, hunkRawIndices, onHunkExclude]);

	return (
		<DiffTable
			lines={lines}
			layout={diffLayout}
			onHunkHeaderDragStart={handleHunkDragStart}
			onHunkAddActive={(headerIdx: number) => addHunkToEditor(headerIdx, 'active')}
			onHunkAddQuickPick={(headerIdx: number) => addHunkToEditor(headerIdx, 'quickpick')}
			onHunkExclude={onHunkExclude ? handleHunkExclude : undefined}
			activeNodeContext={activeNodeContext}
			coveredHeaderIndices={coveredHeaderIndices}
			hideCovered={hideCovered}
			selectedHeaderIndices={selectedHeaderIndices}
			searchActive={searchActive}
			searchMatchedHeaderIndices={searchMatchInfo.matchedHeaderIndices}
			searchMatchedLineIndices={searchMatchInfo.matchedLineIndices}
			onHunkSelectToggle={handleHunkSelectToggle}
			selectedHunksCount={selectedHeaderIndices.size}
		/>
	);
}


function FileEntry({ file, prNumber, prOwner, prRepo, baseSha, headSha, onHunkAdd, onHunkExclude, onFileExclude, activeNodeContext, coveredHunksSet, fileMissingHunks, selectedHunksSet, onHunkSelect, onFileSelect, fileAllHunks, expanded, onToggleExpanded, searchActive, searchMatched, searchQuery, hideCovered, diffLayout }: { file: ChangedFileInfo, prNumber: number, prOwner: string, prRepo: string, baseSha?: string, headSha?: string, onHunkAdd: (hunks: HunkReference[], mode: 'active' | 'quickpick') => void, onHunkExclude?: (file: string, startLine: number, endLine: number, fp: string | undefined) => void, onFileExclude?: (file: string) => void, activeNodeContext?: string, coveredHunksSet?: Set<string>, fileMissingHunks: any[], selectedHunksSet: Set<string>, onHunkSelect: (k: string, s: boolean) => void, onFileSelect: (hunks: any[], s: boolean) => void, fileAllHunks: any[], expanded: boolean, onToggleExpanded: (expanded: boolean) => void, searchActive: boolean, searchMatched: boolean, searchQuery: string, hideCovered: boolean, diffLayout?: 'inline' | 'sideBySide' }) {
	const allCovered = fileMissingHunks.length === 0;

	const { text, className } = statusLabel(file.status);
	const { dir, base } = splitPath(file.fileName);

	const selectedFileHunks = useMemo(() => {
		return fileAllHunks.filter((h: any) => selectedHunksSet.has(`${h.file}:${h.startLine}:${h.endLine}`));
	}, [fileAllHunks, selectedHunksSet]);

	const isAllSelected = fileAllHunks.length > 0 && selectedFileHunks.length === fileAllHunks.length;
	const isIndeterminate = selectedFileHunks.length > 0 && !isAllSelected;

	return (
		<div className={`file-entry${searchActive && searchMatched ? ' file-entry-search-match' : ''}`}>
			<div className={`file-header ${allCovered ? 'file-covered' : ''}`} onClick={() => onToggleExpanded(!expanded)}>
				<div className="file-actions">
					<Tooltip text={expanded ? 'Collapse file' : 'Expand file'}>
						<span className={`expand-icon icon-button ${expanded ? '' : 'closed'}`}>{chevronDownIcon}</span>
					</Tooltip>
					<Tooltip text="Select file hunks">
						<div className="checkbox-wrapper">
							<input
								type="checkbox"
								checked={isAllSelected}
								ref={r => { if (r) r.indeterminate = isIndeterminate; }}
								onChange={(e) => onFileSelect(fileAllHunks, e.target.checked)}
								onClick={(e) => e.stopPropagation()}
							/>
						</div>
					</Tooltip>
					{(() => {
						// What to add depends on whether the user has checkbox-selected
						// specific hunks: if so, add only those; otherwise default to
						// every uncovered hunk in this file (the menu label promises
						// "Add file hunks", which should do something useful even
						// without an explicit selection).
						const payloads = selectedFileHunks.length > 0 ? selectedFileHunks : fileMissingHunks;
						const addLabel = selectedFileHunks.length > 0
							? `Add ${selectedFileHunks.length} selected hunks`
							: `Add ${fileMissingHunks.length} missing hunk${fileMissingHunks.length === 1 ? '' : 's'} to end of tour`;
						const sectionLabel = selectedFileHunks.length > 0
							? `Add ${selectedFileHunks.length} selected hunks to section…`
							: `Add ${fileMissingHunks.length} missing hunk${fileMissingHunks.length === 1 ? '' : 's'} to section…`;
						const menuItems: OverflowMenuItem[] = [
							{
								key: 'add',
								icon: addIcon,
								label: addLabel,
								disabled: payloads.length === 0,
								onSelect: () => { onHunkAdd(payloads, 'active'); onFileSelect(fileMissingHunks, false); },
							},
							{
								key: 'add-section',
								icon: listTree,
								label: sectionLabel,
								disabled: payloads.length === 0,
								onSelect: () => { onHunkAdd(payloads, 'quickpick'); onFileSelect(fileMissingHunks, false); },
							},
						];
						if (onFileExclude) {
							menuItems.push({
								key: 'exclude',
								icon: eyeClosedIcon,
								label: 'Exclude entire file from tour',
								onSelect: () => onFileExclude(file.fileName),
							});
						}
						return <OverflowMenu items={menuItems} title="File actions" />;
					})()}
				</div>
				<span className={`file-status ${className}`}>{text}</span>
				<span className="file-name">
					{dir && <span className="file-path">{dir}</span>}
					{file.previousFileName && file.status === 'renamed' ? (
						<span className="file-path"> &larr; {file.previousFileName}</span>
					) : null}
					<span className="file-basename">{base}</span>
				</span>
				{(file.additions !== undefined || file.deletions !== undefined) && (
					<span className="file-stats">
						{file.additions !== undefined && <span className="additions">+{file.additions}</span>}
						{file.additions !== undefined && file.deletions !== undefined && ' '}
						{file.deletions !== undefined && <span className="deletions">-{file.deletions}</span>}
					</span>
				)}
			</div>
			{expanded && file.patch && (
				<div className="file-diff">
					<DiffView
						patch={file.patch}
						fileName={file.fileName}
						previousFile={file.previousFileName}
						blobSha={file.blobSha}
						prNumber={prNumber}
						prOwner={prOwner}
						prRepo={prRepo}
						baseSha={baseSha}
						headSha={headSha}
						onHunkAdd={onHunkAdd}
						onHunkExclude={onHunkExclude}
						activeNodeContext={activeNodeContext}
						coveredHunksSet={coveredHunksSet}
						selectedHunksSet={selectedHunksSet}
						onHunkSelect={onHunkSelect}
						onClearHunksSelection={() => onFileSelect(fileMissingHunks, false)}
						searchQuery={searchQuery}
						searchActive={searchActive}
						hideCovered={hideCovered}
						diffLayout={diffLayout}
					/>
				</div>
			)}
			{expanded && !file.patch && (
				<div className="file-diff no-diff">Binary file or no diff available</div>
			)}
		</div>
	);
}

export const ChangedFilesOverview = ({ title, number, owner, repo, baseSha, headSha, files, onHunkAdd, onHunkExclude, onFileExclude, activeNodeContext, codeTourHunks = [], exclusions = [], onAddAllMissing, diffLayout }: ChangedFilesOverviewProps) => {
	const totalAdditions = files.reduce((sum, f) => sum + (f.additions ?? 0), 0);
	const totalDeletions = files.reduce((sum, f) => sum + (f.deletions ?? 0), 0);
	const [selectedHunksSet, setSelectedHunksSet] = useState<Set<string>>(new Set());
	const [searchQuery, setSearchQuery] = useState('');
	const [hideCovered, setHideCovered] = useState(false);
	const [expandedFiles, setExpandedFiles] = useState<Record<string, boolean>>({});
	const normalizedSearchQuery = searchQuery.trim().toLowerCase();
	const searchActive = normalizedSearchQuery.length > 0;

	const handleHunkSelect = useCallback((hunkKey: string, selected: boolean) => {
		setSelectedHunksSet(prev => {
			const next = new Set(prev);
			if (selected) next.add(hunkKey);
			else next.delete(hunkKey);
			return next;
		});
	}, []);

	const handleFileSelect = useCallback((fileMissingHunks: any[], selected: boolean) => {
		setSelectedHunksSet(prev => {
			const next = new Set(prev);
			for (const h of fileMissingHunks) {
				const key = `${h.file}:${h.startLine}:${h.endLine}`;
				if (selected) next.add(key);
				else next.delete(key);
			}
			return next;
		});
	}, []);

	// Coverage by edit-content fingerprint, matching the banner's
	// computeNewInPrCount in viewerModel.ts. Pinned tour hunks are skipped:
	// a hunk pinned as historical context shouldn't claim coverage of the
	// PR's current state at the same location. Without this, the banner
	// reports "N uncovered" while the right pane reports 100% covered.
	const coveredFingerprintsByFile = useMemo(() => {
		const out = new Map<string, Set<string>>();
		const add = (file: string, fp: string) => {
			let s = out.get(file);
			if (!s) { s = new Set(); out.set(file, s); }
			s.add(fp);
		};
		for (const ch of codeTourHunks) {
			if (ch.pinned) {
				continue;
			}
			const fp = editContentFingerprint(ch.patch);
			if (fp === undefined) {
				continue;
			}
			add(ch.file, fp);
			if (ch.previousFile) {
				add(ch.previousFile, fp);
			}
		}
		return out;
	}, [codeTourHunks]);

	// Keep emitting a line-range covered set for the children (DiffView uses
	// it for per-row styling and the "hide covered" filter). It is derived
	// from the fingerprint match: a PR hunk's line range is "covered" iff a
	// non-pinned tour hunk has the same edit fingerprint.
	const coveredHunksSet = useMemo(() => {
		const set = new Set<string>();
		const matchesExclusion = (fileName: string, startLine: number, endLine: number): boolean => {
			for (const e of exclusions) {
				const fileMatch = isGlob(e.file) ? matchesGlob(e.file, fileName) : e.file === fileName;
				if (!fileMatch) continue;
				const wholeFile = e.startLine === undefined && e.endLine === undefined;
				if (wholeFile || (e.startLine === startLine && e.endLine === endLine)) return true;
			}
			return false;
		};
		for (const file of files) {
			if (!file.patch) continue;
			const fps = coveredFingerprintsByFile.get(file.fileName)
				?? (file.previousFileName ? coveredFingerprintsByFile.get(file.previousFileName) : undefined);
			const rawLines = file.patch.split('\n');
			const lines = parsePatch(file.patch);
			const ranges = computeHunkRanges(lines);
			const hunkRawIndices: number[] = [];
			for (let i = 0; i < rawLines.length; i++) {
				if (rawLines[i].startsWith('@@')) {
					hunkRawIndices.push(i);
				}
			}
			for (const [headerIdx, range] of ranges.entries()) {
				const key = `${file.fileName}:${range.startLine}:${range.endLine}`;
				// Excluded PR hunks count as covered so the progress bar /
				// "all covered" file styling update immediately after the
				// author clicks the exclude button. The drift / coverage
				// tools already short-circuit them in the same way.
				if (matchesExclusion(file.fileName, range.startLine, range.endLine)) {
					set.add(key);
					continue;
				}
				if (!fps || fps.size === 0) continue;
				const parsedHunkIdx = lines.slice(0, headerIdx + 1).filter(l => l.type === 'hunk-header').length - 1;
				const rawStart = hunkRawIndices[parsedHunkIdx];
				const rawEnd = parsedHunkIdx + 1 < hunkRawIndices.length
					? hunkRawIndices[parsedHunkIdx + 1]
					: rawLines.length;
				const fp = editContentFingerprint(rawLines.slice(rawStart, rawEnd).join('\n'));
				if (fp !== undefined && fps.has(fp)) {
					set.add(key);
				}
			}
		}
		return set;
	}, [files, coveredFingerprintsByFile, exclusions]);

	const { totalHunks, missingHunks, fileAllHunks } = useMemo(() => {
		let total = 0;
		const missing: any[] = [];
		const allHunksMap = new Map<string, any[]>();
		for (const file of files) {
			if (!file.patch) continue;
			const lines = parsePatch(file.patch);
			const rawLines = file.patch.split('\n');
			const ranges = computeHunkRanges(lines);

			const fileHunks: any[] = [];
			const hunkRawIndices: number[] = [];
			for (let i = 0; i < rawLines.length; i++) {
				if (rawLines[i].startsWith('@@')) {
					hunkRawIndices.push(i);
				}
			}

			for (const [headerIdx, range] of ranges.entries()) {
				total++;
				const hunkKey = `${file.fileName}:${range.startLine}:${range.endLine}`;

				const parsedHunkIdx = lines.slice(0, headerIdx + 1).filter(l => l.type === 'hunk-header').length - 1;
				const rawStart = hunkRawIndices[parsedHunkIdx];
				const rawEnd = parsedHunkIdx + 1 < hunkRawIndices.length
					? hunkRawIndices[parsedHunkIdx + 1]
					: rawLines.length;
				const hunkPatch = rawLines.slice(rawStart, rawEnd).join('\n');

				const hunkObj = {
					file: file.fileName,
					startLine: range.startLine,
					endLine: range.endLine,
							patch: hunkPatch,
					previousFile: file.previousFileName,
					baseBlob: file.blobSha,
					baseSha,
					headSha,
					prNumber: number,
					prOwner: owner,
					prRepo: repo
				};

				fileHunks.push(hunkObj);

				if (!coveredHunksSet.has(hunkKey)) {
					missing.push(hunkObj);
				}
			}
			allHunksMap.set(file.fileName, fileHunks);
		}
		return { totalHunks: total, missingHunks: missing, fileAllHunks: allHunksMap };
	}, [files, coveredHunksSet, baseSha, headSha, number, owner, repo]);

	const coveredHunks = totalHunks - missingHunks.length;

	// Split the coverage tally into "in tour" vs "excluded" so the progress
	// bar can render two stacked segments. Both still count toward the
	// numerator -- exclusion intentionally satisfies coverage in the same
	// way as a tour hunk -- but reviewers see at a glance which slice is
	// narrated and which slice was opted out.
	const excludedHunkCount = useMemo(() => {
		const matches = (fileName: string, startLine: number, endLine: number): boolean => {
			for (const e of exclusions) {
				const fileMatch = isGlob(e.file) ? matchesGlob(e.file, fileName) : e.file === fileName;
				if (!fileMatch) continue;
				const wholeFile = e.startLine === undefined && e.endLine === undefined;
				if (wholeFile || (e.startLine === startLine && e.endLine === endLine)) return true;
			}
			return false;
		};
		let n = 0;
		for (const [, fileHunks] of fileAllHunks) {
			for (const h of fileHunks) {
				if (matches(h.file, h.startLine, h.endLine)) n++;
			}
		}
		return n;
	}, [fileAllHunks, exclusions]);
	const tourCoveredHunks = Math.max(0, coveredHunks - excludedHunkCount);
	const tourCoveredPercent = totalHunks === 0 ? 0 : (tourCoveredHunks / totalHunks) * 100;
	const excludedPercent = totalHunks === 0 ? 0 : (excludedHunkCount / totalHunks) * 100;

	const visibleFiles = useMemo(() => {
		return files.filter(file => {
			const matchesSearch = !searchActive || matchesFileSearch(file, normalizedSearchQuery);
			if (!matchesSearch) {
				return false;
			}

			if (!hideCovered) {
				return true;
			}

			if (!file.patch) {
				return true;
			}

			return missingHunks.some(h => h.file === file.fileName);
		});
	}, [files, hideCovered, missingHunks, normalizedSearchQuery, searchActive]);

	const allSelectedHunks = useMemo(() => {
		const allSelected: any[] = [];
		fileAllHunks.forEach((hunks) => {
			allSelected.push(...hunks.filter(h => selectedHunksSet.has(`${h.file}:${h.startLine}:${h.endLine}`)));
		});
		return allSelected;
	}, [fileAllHunks, selectedHunksSet]);

	const handleToggleExpanded = useCallback((fileName: string, expanded: boolean) => {
		setExpandedFiles(prev => ({
			...prev,
			[fileName]: expanded,
		}));
	}, []);

	return (
		<div className="code-tour-changes">
			<h2>All Changes for Change Tour &mdash; {title} <a>#{number}</a></h2>
			<div className="summary">
				{searchActive ? `${visibleFiles.length} of ${files.length} files match search` : `${files.length} changed file${files.length !== 1 ? 's' : ''}`} with{' '}
				<span className="additions">+{totalAdditions}</span> and{' '}
				<span className="deletions">-{totalDeletions}</span>
			</div>
			<div className="changes-sticky-stack">
				{totalHunks > 0 && (
					<div className="exhaustiveness-check">
						<div className="exhaustiveness-header">
							<span title={excludedHunkCount > 0
								? `${tourCoveredHunks} hunk${tourCoveredHunks === 1 ? '' : 's'} in the tour, ${excludedHunkCount} excluded by marker, ${missingHunks.length} missing.`
								: undefined}>
								Covered Changes: {coveredHunks} / {totalHunks}
								{excludedHunkCount > 0 && (
									<span className="excluded-count-suffix"> ({excludedHunkCount} excluded)</span>
								)}
							</span>
							<div className="global-actions">
								<button
									disabled={allSelectedHunks.length === 0}
									onClick={() => {
										if (allSelectedHunks.length > 0) {
											onHunkAdd(allSelectedHunks, 'active');
											setSelectedHunksSet(new Set());
										}
									}}>
									{allSelectedHunks.length > 0 ? `Add ${allSelectedHunks.length} Selected` : 'Add Selected'}
								</button>
								{missingHunks.length > 0 && onAddAllMissing && (
									<button onClick={() => onAddAllMissing(missingHunks)}>Add All Missing</button>
								)}
							</div>
						</div>
						<div className="progress-bar-container">
							<div
								className="progress-bar progress-bar-tour"
								style={{ width: `${tourCoveredPercent}%` }}
								title={`${tourCoveredHunks} of ${totalHunks} hunk${totalHunks === 1 ? '' : 's'} narrated in the tour.`}
							/>
							<div
								className="progress-bar progress-bar-excluded"
								style={{ width: `${excludedPercent}%` }}
								title={`${excludedHunkCount} of ${totalHunks} hunk${totalHunks === 1 ? '' : 's'} excluded from tour. Counted toward coverage but not narrated.`}
							/>
						</div>
					</div>
				)}
				<div className="changes-search-row">
					<div className="changes-search-controls">
						<input
							className="changes-search-input"
							type="search"
							placeholder="Search files, hunks, or patch text"
							value={searchQuery}
							onChange={e => setSearchQuery(e.target.value)}
						/>
						{searchActive && (
							<button className="changes-search-clear" onClick={() => setSearchQuery('')}>
								Clear
							</button>
						)}
					</div>
					<Tooltip text="Show hunks already covered by Change Tour nodes">
						<label className="changes-toggle-covered">
							<div className="checkbox-wrapper">
								<input
									type="checkbox"
									checked={hideCovered}
									onChange={e => setHideCovered(e.target.checked)}
								/>
							</div>
							<span>Show covered</span>
						</label>
					</Tooltip>
				</div>
			</div>
			<div className="changed-files-list">
				{visibleFiles.length > 0 ? visibleFiles.map(file => {
					const fileMissingHunks = missingHunks.filter(h => h.file === file.fileName);
					const fileSearchMatch = matchesFileSearch(file, normalizedSearchQuery);
					const expanded = searchActive && fileSearchMatch ? true : (expandedFiles[file.fileName] ?? fileMissingHunks.length > 0);
					return (
						<FileEntry
							key={file.fileName}
							file={file}
							prNumber={number}
							prOwner={owner}
							prRepo={repo}
							baseSha={baseSha}
							headSha={headSha}
							onHunkAdd={onHunkAdd}
							onHunkExclude={onHunkExclude}
							onFileExclude={onFileExclude}
							activeNodeContext={activeNodeContext}
							coveredHunksSet={coveredHunksSet}
							fileMissingHunks={fileMissingHunks}
							fileAllHunks={fileAllHunks.get(file.fileName) || []}
							selectedHunksSet={selectedHunksSet}
							onHunkSelect={handleHunkSelect}
							onFileSelect={handleFileSelect}
							expanded={expanded}
							onToggleExpanded={expandedValue => handleToggleExpanded(file.fileName, expandedValue)}
							searchActive={searchActive}
							searchMatched={fileSearchMatch}
							searchQuery={searchQuery}
							hideCovered={hideCovered}
							diffLayout={diffLayout}
						/>
					);
				}) : (
					<div className="changes-empty-state">No files match this search.</div>
				)}
			</div>
		</div>
	);
};